"""
Markdown报告生成器
整合所有分析维度，生成结构化的Markdown报告
"""
from typing import Dict, Any, List, Optional
from datetime import datetime

from app.services.research_engine.analyzers.analyzer_output import AnalyzerOutput


class MarkdownReportGenerator:
    """Markdown报告生成器"""

    def __init__(self):
        """初始化报告生成器"""
        pass

    def generate_full_report(
        self,
        query: str,
        tldr: AnalyzerOutput,
        fundamental: Optional[AnalyzerOutput] = None,
        technical: Optional[AnalyzerOutput] = None,
        competitor: Optional[AnalyzerOutput] = None,
        risk: Optional[AnalyzerOutput] = None,
        symbol: str = "Unknown",
    ) -> str:
        """
        生成完整的Deep Research报告

        Args:
            query: 用户查询
            tldr: TL;DR分析结果
            fundamental: 基本面分析结果
            technical: 技术分析结果
            competitor: 竞品分析结果
            risk: 风险评估结果
            symbol: 币种符号

        Returns:
            str: Markdown格式的完整报告
        """
        report_parts = []

        # 1. 报告头部
        report_parts.append(self._generate_header(query, symbol))

        # 2. TL;DR摘要
        report_parts.append(self._generate_tldr_section(tldr))

        # 3. 基本面分析
        if fundamental and not fundamental.error:
            report_parts.append(self._generate_section(
                title="📊 基本面分析",
                content=fundamental.data.get("analysis", ""),
                metadata=self._format_metadata(fundamental)
            ))

        # 4. 技术分析
        if technical and not technical.error:
            report_parts.append(self._generate_section(
                title="📈 技术分析",
                content=technical.data.get("analysis", ""),
                metadata=self._format_metadata(technical)
            ))

        # 5. 竞品分析
        if competitor and not competitor.error:
            report_parts.append(self._generate_section(
                title="🔄 竞品对比",
                content=competitor.data.get("analysis", ""),
                metadata=self._format_metadata(competitor)
            ))

        # 6. 风险评估
        if risk and not risk.error:
            report_parts.append(self._generate_section(
                title="⚠️ 风险评估",
                content=risk.data.get("analysis", ""),
                metadata=self._format_metadata(risk)
            ))

        # 7. 报告尾部
        report_parts.append(self._generate_footer())

        return "\n\n".join(report_parts)

    def _generate_header(self, query: str, symbol: str) -> str:
        """生成报告头部"""
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        return f"""# 🔍 Deep Research Report: {symbol}

**查询**: {query}

**生成时间**: {now}

---
"""

    def _generate_tldr_section(self, tldr: AnalyzerOutput) -> str:
        """生成TL;DR章节"""
        if tldr.error:
            return f"""## 🎯 TL;DR

⚠️ TL;DR生成失败: {tldr.error_message}
"""

        data = tldr.data
        judgment = data.get("judgment", "NEUTRAL")
        judgment_emoji = data.get("judgment_emoji", "🟡")
        confidence = data.get("confidence", 50)
        confidence_level = data.get("confidence_level", "中等")
        summary = data.get("summary", "")

        return f"""## 🎯 TL;DR

### 核心判断
{judgment_emoji} **{judgment}** (置信度: {confidence}% - {confidence_level})

### 一句话总结
{summary}

---
"""

    def _generate_section(
        self,
        title: str,
        content: str,
        metadata: str = ""
    ) -> str:
        """生成通用章节"""
        section = f"""## {title}

{content}
"""

        if metadata:
            section += f"\n{metadata}\n"

        section += "\n---\n"

        return section

    def _format_metadata(self, analyzer_output: AnalyzerOutput) -> str:
        """格式化分析器元数据"""
        metadata_parts = []

        # 模型信息
        model_info = f"**模型**: {analyzer_output.model_used}"
        if analyzer_output.fallback_used:
            model_info += " (使用Fallback)"
        metadata_parts.append(model_info)

        # 生成时间
        metadata_parts.append(f"**生成时间**: {analyzer_output.generation_time_ms}ms")

        # 验证状态
        if not analyzer_output.validation_passed:
            metadata_parts.append("**验证状态**: ⚠️ 部分数据使用默认值补全")

        return "\n".join([f"<small>{m}</small>" for m in metadata_parts])

    def _generate_footer(self) -> str:
        """生成报告尾部"""
        return f"""---

## 📝 免责声明

本报告由AI自动生成，仅供参考。加密货币投资存在风险，请谨慎决策。

**生成工具**: Web3Search Deep Research Engine
**支持模型**: Qwen 2.5 72B, DeepSeek Chat

---

*Report generated by Web3Search - Your AI-Powered Crypto Research Assistant*
"""

    def generate_summary_table(
        self,
        analyses: List[AnalyzerOutput]
    ) -> str:
        """
        生成分析汇总表

        Args:
            analyses: 所有分析结果列表

        Returns:
            str: Markdown表格
        """
        table = """| 分析维度 | 状态 | 生成时间 | 模型 |
|----------|------|----------|------|
"""

        for analysis in analyses:
            if analysis.error:
                status = "❌ 失败"
            elif analysis.validation_passed:
                status = "✅ 成功"
            else:
                status = "⚠️ 部分成功"

            model = analysis.model_used
            if analysis.fallback_used:
                model += " (FB)"

            table += f"| {analysis.analyzer_name} | {status} | {analysis.generation_time_ms}ms | {model} |\n"

        return table


# 全局单例
report_generator = MarkdownReportGenerator()
