/**
 * Deep Research Domain Types
 *
 * Glass Box UX streaming events and tokenomics analysis outputs.
 * These types mirror the backend definitions for type-safe SSE handling.
 *
 * @module types/deep-research
 */

// ============================================================================
// Glass Box UX Event Types
// ============================================================================

/**
 * Tool call event emitted during research pipeline execution.
 * Used for real-time visibility into agent operations.
 */
export interface ToolCallEvent {
  type: 'tool_call'
  /** The tool being invoked */
  tool: 'search' | 'market_data' | 'security_check' | 'synthesis' | 'plan_generation'
  /** Search query or input (if applicable) */
  query?: string
  /** Data provider name (e.g., 'DexScreener', 'GoPlus') */
  provider?: string
  /** Execution time in milliseconds */
  latency_ms: number
  /** Brief summary of the result */
  result_summary: string
  /** Number of sources retrieved (for search operations) */
  source_count?: number
  /** Current status of the tool call */
  status: 'started' | 'completed' | 'failed'
  /** ISO8601 timestamp */
  timestamp?: string
}

/**
 * Thinking event showing the agent's reasoning process.
 * Provides transparency into decision-making during research.
 */
export interface ThinkingEvent {
  type: 'thinking'
  /** Current research stage */
  stage: 'planning' | 'searching' | 'analyzing' | 'synthesizing'
  /** The agent's thought or reasoning */
  thought: string
  /** ISO8601 timestamp */
  timestamp?: string
}

/**
 * Union type for all Glass Box events
 */
export type GlassBoxEvent = ToolCallEvent | ThinkingEvent

// ============================================================================
// Tokenomics Analysis Types
// ============================================================================

/**
 * Risk scorecard with 0-100 score and rating label
 */
export interface TokenomicsScorecard {
  /** Risk score from 0 (safest) to 100 (highest risk) */
  score: number
  /** Human-readable rating */
  rating: 'Ponzi Risk' | 'Speculative' | 'Sustainable'
  /** Color indicator for UI */
  color: 'red' | 'yellow' | 'green'
}

/**
 * Complete tokenomics analysis result from deep research
 */
export interface TokenomicsAnalysis {
  scorecard: TokenomicsScorecard
  red_flags: string[]
  analysis: {
    supply_dynamics: {
      circulating_supply?: string
      max_supply?: string
      fdv?: string
      inflation_rate?: string
      findings: string
    }
    allocation: {
      insider_percentage?: number
      centralization_risk: 'Low' | 'Medium' | 'High'
      breakdown: Record<string, number>
      findings: string
    }
    vesting: {
      next_unlock?: string
      monthly_sell_pressure?: string
      findings: string
    }
    value_accrual: {
      mechanism: string
      yield_type: 'Real Yield' | 'Ponzi Yield' | 'None'
      findings: string
    }
    sustainability: {
      death_spiral_risk: 'Low' | 'Medium' | 'High'
      findings: string
    }
  }
  stress_test: {
    scenario: string
    treasury_runway?: string
    staking_impact?: string
    findings: string
  }
  verdict: {
    recommendation: 'Short-term flip' | 'Long-term hold' | 'Avoid'
    summary: string
  }
}

// ============================================================================
// Adversarial Q&A Types
// ============================================================================

/**
 * A critical follow-up question generated by adversarial analysis
 */
export interface AdversarialQuestion {
  /** The pointed question to consider */
  question: string
  /** Why this question matters for risk assessment */
  rationale: string
}

// ============================================================================
// Extended Research Result
// ============================================================================

/**
 * Extended deep research result including all analysis outputs
 */
export interface DeepResearchResult {
  /** Main research content (markdown) */
  content: string
  /** Session identifier */
  session_id?: string
  /** Tokenomics analysis (if research_type is 'tokenomics') */
  tokenomics?: TokenomicsAnalysis
  /** Generated adversarial questions */
  adversarial_questions?: AdversarialQuestion[]
  /** Research metadata */
  metadata?: {
    research_type?: string
    total_sources?: number
    duration_ms?: number
    from_cache?: boolean
    contract_address?: string
    chain?: string
  }
}
