/**
 * Deep Research Types
 * Async research task management
 * Part of Week 2 T11: Deep Research async pipeline
 */

export type ResearchStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled'
export type ResearchDepth = 'quick' | 'standard' | 'deep'

/**
 * Research type for specialized analysis modes
 */
export type ResearchType = 
  | 'general'           // 通用研究
  | 'tokenomics'        // 代币经济学审计
  | 'security'          // 安全审计 (未来扩展)
  | 'competitive'       // 竞品分析 (未来扩展)

/**
 * Tokenomics scorecard output
 */
export interface TokenomicsScorecard {
  score: number        // 0-100
  rating: 'Ponzi Risk' | 'Speculative' | 'Sustainable'
  color: 'red' | 'yellow' | 'green'
}

/**
 * Tokenomics analysis result
 */
export interface TokenomicsAnalysis {
  scorecard: TokenomicsScorecard
  red_flags: string[]
  analysis: {
    supply_dynamics: {
      circulating_supply?: string
      max_supply?: string
      fdv?: string
      inflation_rate?: string
      findings: string
    }
    allocation: {
      insider_percentage?: number
      centralization_risk: 'Low' | 'Medium' | 'High'
      breakdown: Record<string, number>
      findings: string
    }
    vesting: {
      next_unlock?: string
      monthly_sell_pressure?: string
      findings: string
    }
    value_accrual: {
      mechanism: string
      yield_type: 'Real Yield' | 'Ponzi Yield' | 'None'
      findings: string
    }
    sustainability: {
      death_spiral_risk: 'Low' | 'Medium' | 'High'
      findings: string
    }
  }
  stress_test: {
    scenario: string
    treasury_runway?: string
    staking_impact?: string
    findings: string
  }
  verdict: {
    recommendation: 'Short-term flip' | 'Long-term hold' | 'Avoid'
    summary: string
  }
}

/**
 * Research plan generated by the model
 */
export interface ResearchPlan {
  query_understanding: string
  research_dimensions: Array<{
    dimension: string
    importance: 'high' | 'medium' | 'low'
    description: string
  }>
  search_queries: Array<{
    query: string
    purpose: string
    target_dimension: string
  }>
  expected_challenges: string[]
}

/**
 * Structured research finding with evidence
 */
export interface ResearchFinding {
  finding: string
  evidence: string
  sources: number[]
  confidence: number
}

/**
 * Enhanced research result with structured analysis
 */
export interface EnhancedResearchResult {
  executive_summary: string
  detailed_analysis: {
    sections: Array<{
      title: string
      content: string
      dimension: string
    }>
  }
  key_findings: ResearchFinding[]
  risks_and_uncertainties: {
    limitations: string[]
    uncertainties: string[]
    potential_biases: string[]
  }
  conclusion: {
    summary: string
    recommendations: string[]
    future_research: string[]
  }
  metadata: {
    total_sources_analyzed: number
    overall_confidence: number
    research_depth: ResearchDepth
  }
}

export interface ResearchSource {
  url: string
  title: string
  snippet: string
  relevance_score: number
  accessed_at: string
}

export interface ResearchCitation {
  source_id: string
  quote: string
  page_number?: number
  relevance_score: number
}

// ============================================
// Glass Box UX - Real-time Process Visibility
// ============================================

/**
 * Tool call event for Glass Box UX
 * Emitted when the research pipeline invokes external tools/APIs
 */
export interface ToolCallEvent {
  type: 'tool_call'
  tool: 'search' | 'market_data' | 'security_check' | 'synthesis' | 'plan_generation'
  query?: string
  provider?: string
  latency_ms: number
  result_summary: string
  source_count?: number
  status: 'started' | 'completed' | 'failed'
  timestamp?: string
}

/**
 * Thinking event for Glass Box UX
 * Emitted to show the agent's reasoning process
 */
export interface ThinkingEvent {
  type: 'thinking'
  stage: 'planning' | 'searching' | 'analyzing' | 'synthesizing'
  thought: string
  timestamp?: string
}

/**
 * Union type for all Glass Box SSE events
 */
export type GlassBoxEvent = ToolCallEvent | ThinkingEvent

/**
 * Extended SSE event type including Glass Box events
 */
export interface DeepResearchSSEEvent {
  type: 'progress' | 'content' | 'complete' | 'error' | 'tool_call' | 'thinking'
  stage?: string
  section?: string
  content?: string
  session_id?: string
  timestamp?: string
  // Tool call specific
  tool?: ToolCallEvent['tool']
  provider?: string
  latency_ms?: number
  result_summary?: string
  source_count?: number
  status?: ToolCallEvent['status']
  // Thinking specific
  thought?: string
}

export interface DeepResearchRequest {
  query: string
  research_type?: ResearchType    // 研究类型: general, tokenomics, security, competitive
  research_depth?: ResearchDepth
  max_sources?: number
  focus_areas?: string[]
  model?: string
  model_provider?: string
  temperature?: number
  conversation_id?: string
  metadata?: Record<string, unknown>
}

export interface DeepResearchTask {
  id: string
  user_id?: string
  client_session_id?: string
  conversation_id?: string
  query: string
  status: ResearchStatus
  research_depth: ResearchDepth
  max_sources: number
  focus_areas: string[]
  model_id?: string
  model_provider?: string
  temperature: number
  result?: ResearchResult
  summary?: string
  answer?: string
  sources: ResearchSource[]
  citations: ResearchCitation[]
  progress_percent: number
  current_step?: string
  steps_completed: number
  total_steps: number
  tokens_prompt: number
  tokens_completion: number
  cost_usd: number
  started_at?: string
  completed_at?: string
  duration_ms?: number
  error_code?: string
  error_message?: string
  retry_count: number
  created_at: string
  updated_at: string
  expires_at: string
  metadata: Record<string, unknown>
  tags: string[]
}

/**
 * Adversarial question generated for critical analysis
 */
export interface AdversarialQuestion {
  /** The pointed question to consider */
  question: string
  /** Why this question matters for risk assessment */
  rationale: string
}

export interface ResearchResult {
  summary: string
  answer: string
  key_findings: string[]
  sources: ResearchSource[]
  citations: ResearchCitation[]
  research_depth: ResearchDepth
  total_sources: number
  total_citations: number
  confidence_score: number
  /** Generated adversarial questions for critical analysis */
  adversarial_questions?: AdversarialQuestion[]
}

export interface ResearchProgress {
  task_id: string
  status: ResearchStatus
  progress_percent: number
  current_step?: string
  steps_completed: number
  total_steps: number
  estimated_time_remaining?: number
  timestamp: string
  [key: string]: unknown
}

export interface ResearchListParams {
  user_id?: string
  status?: ResearchStatus
  research_depth?: ResearchDepth
  limit?: number
  offset?: number
  from_date?: string
  to_date?: string
}

export interface ResearchListResponse {
  tasks: DeepResearchTask[]
  total: number
  limit: number
  offset: number
}

export interface ResearchStepUpdate {
  step_name: string
  step_number: number
  total_steps: number
  progress_percent: number
  message?: string
  timestamp: string
  [key: string]: unknown
}

// WebSocket/SSE events for real-time updates
export interface ResearchSSEvent {
  event: 'research.started' | 'research.progress' | 'research.step' | 'research.completed' | 'research.failed'
  data: {
    task_id: string
    timestamp: string
    [key: string]: unknown
  }
}

export interface ResearchStartedEvent extends ResearchSSEvent {
  event: 'research.started'
  data: {
    task_id: string
    timestamp: string
    query: string
    estimated_duration: number
  }
}

export interface ResearchProgressEvent extends ResearchSSEvent {
  event: 'research.progress'
  data: ResearchProgress
}

export interface ResearchStepEvent extends ResearchSSEvent {
  event: 'research.step'
  data: ResearchStepUpdate & { task_id: string }
}

export interface ResearchCompletedEvent extends ResearchSSEvent {
  event: 'research.completed'
  data: {
    task_id: string
    timestamp: string
    result: ResearchResult
    duration_ms: number
    cost_usd: number
  }
}

export interface ResearchFailedEvent extends ResearchSSEvent {
  event: 'research.failed'
  data: {
    task_id: string
    timestamp: string
    error_code: string
    error_message: string
    retry_count: number
  }
}

// Database row type (for internal use)
export interface DeepResearchTaskRow {
  id: string
  user_id: string | null
  client_session_id: string | null
  conversation_id: string | null
  query: string
  status: ResearchStatus
  research_depth: ResearchDepth
  max_sources: number
  focus_areas: string[] | null
  model_id: string | null
  model_provider: string | null
  temperature: number
  result: unknown | null
  summary: string | null
  answer: string | null
  sources: unknown | null
  citations: unknown | null
  progress_percent: number
  current_step: string | null
  steps_completed: number
  total_steps: number
  tokens_prompt: number
  tokens_completion: number
  cost_usd: number
  started_at: string | null
  completed_at: string | null
  duration_ms: number | null
  error_code: string | null
  error_message: string | null
  retry_count: number
  created_at: string
  updated_at: string
  expires_at: string
  metadata: unknown | null
  tags: string[] | null
}
