/**
 * Hono Context Type Extensions
 * Extend Hono's ContextVariableMap to add custom context variables
 */

import 'hono'
import type { Toucan } from 'toucan-js'

declare module 'hono' {
  interface ContextVariableMap {
    /**
     * Unique request ID generated by logger middleware
     * Used for request tracing and logging
     */
    requestId: string

    /**
     * Sentry instance for error tracking
     * Created by sentryMiddleware
     */
    sentry?: Toucan

    /**
     * Current authenticated user
     * Set by auth middleware
     */
    currentUser?: {
      id: string
      email?: string
      username?: string
    }
  }
}

// Ensure this is treated as a module augmentation
export {}
