/**
 * Hono Context Type Extensions
 * Extend Hono's ContextVariableMap to add custom context variables
 */

import 'hono'

declare module 'hono' {
  interface ContextVariableMap {
    /**
     * Unique request ID generated by logger middleware
     * Used for request tracing and logging
     */
    requestId: string
  }
}

// Ensure this is treated as a module augmentation
export {}
