"""
API Schemas
"""
from app.schemas.chat import (
    QuickChatRequest,
    QuickChatResponse,
    DeepResearchRequest,
    DeepResearchResponse,
    StreamChunk,
    ErrorResponse,
    ResearchSection,
)
from app.schemas.report import (
    ReportResponse,
    ReportListResponse,
    ReportSummary,
    ReportQueryParams,
)
from app.schemas.research import (
    # Analyzer Schemas
    TLDRSchema,
    TimeframeSchema,
    SentimentSchema,
    TechnicalSchema,
    OnchainSchema,
    CompetitorSchema,
    TokenomicsSchema,
    RiskSchema,
    ConclusionSchema,
    FullReportSchema,
    # Sub-schemas
    TimeframeMetrics,
    TimeframeAnalysis,
    SocialMetrics,
    PriceMetrics,
    TechnicalIndicators,
    HolderDistribution,
    OnchainMetrics,
    CompetitorMetrics,
    ValuationMultiples,
    SupplyStructure,
    UnlockScheduleItem,
    ValueCapture,
    CatalystItem,
    RiskItem,
    RiskRewardAnalysis,
    ScenarioAnalysisItem,
    CalendarEvent,
    ExecutiveSummary,
    InvestmentOutlook,
    InvestmentOutlookPeriod,
    KeyMetric,
    ConfidenceAssessment,
    InvestmentRecommendation,
    ComparativeAnalysis,
    FinalVerdict,
)

__all__ = [
    # Chat Schemas
    "QuickChatRequest",
    "QuickChatResponse",
    "DeepResearchRequest",
    "DeepResearchResponse",
    "StreamChunk",
    "ErrorResponse",
    "ResearchSection",
    # Report Schemas
    "ReportResponse",
    "ReportListResponse",
    "ReportSummary",
    "ReportQueryParams",
    # Research Analyzer Schemas
    "TLDRSchema",
    "TimeframeSchema",
    "SentimentSchema",
    "TechnicalSchema",
    "OnchainSchema",
    "CompetitorSchema",
    "TokenomicsSchema",
    "RiskSchema",
    "ConclusionSchema",
    "FullReportSchema",
    # Research Sub-schemas
    "TimeframeMetrics",
    "TimeframeAnalysis",
    "SocialMetrics",
    "PriceMetrics",
    "TechnicalIndicators",
    "HolderDistribution",
    "OnchainMetrics",
    "CompetitorMetrics",
    "ValuationMultiples",
    "SupplyStructure",
    "UnlockScheduleItem",
    "ValueCapture",
    "CatalystItem",
    "RiskItem",
    "RiskRewardAnalysis",
    "ScenarioAnalysisItem",
    "CalendarEvent",
    "ExecutiveSummary",
    "InvestmentOutlook",
    "InvestmentOutlookPeriod",
    "KeyMetric",
    "ConfidenceAssessment",
    "InvestmentRecommendation",
    "ComparativeAnalysis",
    "FinalVerdict",
]
