"""
API Schemas
"""
from app.schemas.chat import (
    QuickChatRequest,
    QuickChatResponse,
    DeepResearchRequest,
    DeepResearchResponse,
    StreamChunk,
    ErrorResponse,
    ResearchSection,
)
from app.schemas.report import (
    ReportResponse,
    ReportListResponse,
    ReportSummary,
    ReportQueryParams,
)
from app.schemas.research import (
    # Analyzer Schemas
    TLDRSchema,
    TimeframeSchema,
    SentimentSchema,
    TechnicalSchema,
    OnchainSchema,
    CompetitorSchema,
    TokenomicsSchema,
    RiskSchema,
    ConclusionSchema,
    FullReportSchema,
    # Sub-schemas
    TimeframeMetrics,
    TimeframeAnalysis,
    SocialMetrics,
    PriceMetrics,
    TechnicalIndicators,
    HolderDistribution,
    OnchainMetrics,
    CompetitorMetrics,
    ValuationMultiples,
    SupplyStructure,
    UnlockScheduleItem,
    ValueCapture,
    CatalystItem,
    RiskItem,
    RiskRewardAnalysis,
    ScenarioAnalysisItem,
    CalendarEvent,
    ExecutiveSummary,
    InvestmentOutlook,
    InvestmentOutlookPeriod,
    KeyMetric,
    ConfidenceAssessment,
    InvestmentRecommendation,
    ComparativeAnalysis,
    FinalVerdict,
)
from app.schemas.auth import (
    RegisterRequest,
    RegisterResponse,
    LoginRequest,
    LoginResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    ResetPasswordRequest,
    ResetPasswordResponse,
)
from app.schemas.user import (
    UserInfo,
    UserUpdate,
    UserDeleteRequest,
    UserDeleteResponse,
    PreferencesResponse,
    PreferencesUpdate,
    DataExportResponse,
    MigrationRequest,
    MigrationResponse,
    MigrationResult,
    ConversationMigrationData,
    ReportMigrationData,
)

__all__ = [
    # Chat Schemas
    "QuickChatRequest",
    "QuickChatResponse",
    "DeepResearchRequest",
    "DeepResearchResponse",
    "StreamChunk",
    "ErrorResponse",
    "ResearchSection",
    # Report Schemas
    "ReportResponse",
    "ReportListResponse",
    "ReportSummary",
    "ReportQueryParams",
    # Research Analyzer Schemas
    "TLDRSchema",
    "TimeframeSchema",
    "SentimentSchema",
    "TechnicalSchema",
    "OnchainSchema",
    "CompetitorSchema",
    "TokenomicsSchema",
    "RiskSchema",
    "ConclusionSchema",
    "FullReportSchema",
    # Research Sub-schemas
    "TimeframeMetrics",
    "TimeframeAnalysis",
    "SocialMetrics",
    "PriceMetrics",
    "TechnicalIndicators",
    "HolderDistribution",
    "OnchainMetrics",
    "CompetitorMetrics",
    "ValuationMultiples",
    "SupplyStructure",
    "UnlockScheduleItem",
    "ValueCapture",
    "CatalystItem",
    "RiskItem",
    "RiskRewardAnalysis",
    "ScenarioAnalysisItem",
    "CalendarEvent",
    "ExecutiveSummary",
    "InvestmentOutlook",
    "InvestmentOutlookPeriod",
    "KeyMetric",
    "ConfidenceAssessment",
    "InvestmentRecommendation",
    "ComparativeAnalysis",
    "FinalVerdict",
    # Auth Schemas
    "RegisterRequest",
    "RegisterResponse",
    "LoginRequest",
    "LoginResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "ResetPasswordRequest",
    "ResetPasswordResponse",
    # User Schemas
    "UserInfo",
    "UserUpdate",
    "UserDeleteRequest",
    "UserDeleteResponse",
    "PreferencesResponse",
    "PreferencesUpdate",
    "DataExportResponse",
    "MigrationRequest",
    "MigrationResponse",
    "MigrationResult",
    "ConversationMigrationData",
    "ReportMigrationData",
]
