/**
 * Deep Research Service Layer Types
 * Provides strict type definitions for the research pipeline services
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import type { Env } from '../../types/env'
import type { MarketContext } from '../../lib/context-builders/market-context'
import type { ModelConfig } from '../../lib/model-routing'
import type {
  ResearchDepth,
  ResearchType,
  ResearchSource,
  DeepResearchSSEEvent,
  ToolCallEvent,
  ThinkingEvent,
  TokenomicsScorecard,
} from '../../types/deep-research'

// Re-export common types for convenience
export type { ModelConfig } from '../../lib/model-routing'
export type {
  ResearchDepth,
  ResearchType,
  ResearchSource,
  DeepResearchSSEEvent,
  ToolCallEvent,
  ThinkingEvent,
} from '../../types/deep-research'

/**
 * Research plan generated by the model
 */
export interface GeneratedResearchPlan {
  search_queries: string[]
  plan: string
  parsed_plan?: ParsedResearchPlan | null
}

export interface ParsedResearchPlan {
  query_understanding: string
  research_dimensions?: Array<{
    dimension: string
    importance: 'high' | 'medium' | 'low'
    description: string
  }>
}

/**
 * Normalized search result from any provider
 */
export interface NormalizedSearchResult {
  id: string
  title: string
  url: string
  snippet: string
  relevance_score: number
  provider: string
  raw_data?: unknown
}

/**
 * Source citation extracted from analysis
 */
export interface SourceCitation {
  source_id: number
  title: string
  url: string
  snippet: string
  relevance_score: number
}

/**
 * Analysis result from source processing
 */
export interface SourceAnalysisResult {
  citations: SourceCitation[]
  tokens?: { prompt: number; completion: number }
  cost?: number
}

/**
 * Synthesis options for report generation
 */
export interface SynthesisOptions {
  sources?: NormalizedSearchResult[]
  plan?: ParsedResearchPlan | string
  depth?: ResearchDepth
  researchType?: ResearchType
  marketContext?: MarketContext | null
  systemPrompt?: string
}

/**
 * General research result structure
 */
export interface GeneralResearchResult {
  research_type: 'general'
  summary: string
  answer: string
  key_findings: string[]
  sources: NormalizedSearchResult[]
  citations: SourceCitation[]
  research_depth: ResearchDepth
  total_sources: number
  total_citations: number
  confidence_score: number
  structured_analysis?: unknown
  risks_and_uncertainties?: {
    limitations: string[]
    uncertainties: string[]
  }
  conclusion?: {
    summary: string
    recommendations: string[]
  }
}

/**
 * Tokenomics research result structure
 */
export interface TokenomicsResearchResult {
  research_type: 'tokenomics'
  summary: string
  answer: string
  scorecard: TokenomicsScorecard
  red_flags: string[]
  tokenomics_analysis?: unknown
  stress_test?: unknown
  verdict?: {
    recommendation: string
    summary: string
  }
  data_quality?: {
    transparency_score: number
    missing_data?: string[]
  }
  sources: NormalizedSearchResult[]
  citations: SourceCitation[]
  research_depth: ResearchDepth
  total_sources: number
  total_citations: number
  confidence_score: number
}

/**
 * Union type for all research results
 */
export type StructuredResearchResult = GeneralResearchResult | TokenomicsResearchResult

/**
 * Synthesis result returned by synthesizeFindings
 */
export interface SynthesisResult {
  result: StructuredResearchResult
  summary: string
  answer: string
}

/**
 * Query validation result
 */
export interface QueryValidationResult {
  valid: boolean
  sanitized: string
  error?: string
}

/**
 * Pipeline context passed between stages
 */
export interface ResearchPipelineContext {
  query: string
  conversationId: string
  modelConfig: ModelConfig
  supabase: SupabaseClient
  env: Env
  researchType: ResearchType
  marketContext?: MarketContext | null
}

/**
 * Progress update payload
 */
export interface ProgressUpdate {
  current_step?: string
  steps_completed?: number
  progress_percent?: number
}

/**
 * SSE Emitter interface for streaming
 */
export interface ISSEEmitter {
  emit(event: DeepResearchSSEEvent): void
  emitToolCall(event: Omit<ToolCallEvent, 'type'>): void
  emitThinking(event: Omit<ThinkingEvent, 'type'>): void
  emitProgress(stage: string, content: string): void
  emitContent(section: string, content: string): void
  emitComplete(content: string, sessionId: string): void
  emitError(content: string): void
  cancel(): void
  isCancelled(): boolean
}

/**
 * Research configuration by depth
 */
export interface ResearchConfig {
  temperature: number
  plan_max_tokens: number
  synthesis_max_tokens: number
  max_queries: number
  max_sources: number
}
